---
- hosts: webservers
  become: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: "Install Java"
    apt:
      name: openjdk-8-jdk
      state: present
  - name: "Download tomcat server packages"
    get_url:
      url: https://mirror.olnevhost.net/pub/apache/tomcat/tomcat-8/v8.5.63/bin/apache-tomcat-8.5.63.tar.gz
      dest: /usr/local
  - name: "extract tomcat packages"
    unarchive: 
      src: /usr/local/apache-tomcat-8.5.63.tar.gz
      dest: /usr/local
      remote_src: yes
  - name: "start tomcat service"
    shell: nohup /usr/local/apache-tomcat-8.5.63/bin/startup.sh

